version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "mydb"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1s
    networks:
     - nginx-network
  backend:
    build:
      context: ./spo2back
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3002:3002"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    networks:
      - nginx-network


  frontend:
    build:
      context: ./spo2front
      dockerfile: Dockerfile
    container_name: frontend
    ports: 
      - "3000:3000"
    networks:
      - nginx-network
volumes:
  postgres_data:
networks:
  nginx-network:
    external: true